dist: xenial

language: rust

rust: nightly-2020-01-17

os:
  - linux
  - osx

env:
  matrix:
    - ARCH="x86_64"
    - ARCH="aarch64"

before_script:
  - rustup component add rust-src

script:
  - make build
