name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64, aarch64]
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        rustup component add rust-src
        make build ARCH=${{ matrix.arch }}
    - name: Build docs
      run: make doc ARCH=${{ matrix.arch }}
